"""scrapper values table

Revision ID: 65ccdd723aa2
Revises: cb6ccbfa3627
Create Date: 2018-03-20 16:46:49.711367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65ccdd723aa2'
down_revision = 'cb6ccbfa3627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('selector', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrapper_name'), 'scrapper', ['name'], unique=False)
    op.create_table('scrapper_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrapper_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scrapper_id'], ['scrapper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrapper_values_timestamp'), 'scrapper_values', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrapper_values_timestamp'), table_name='scrapper_values')
    op.drop_table('scrapper_values')
    op.drop_index(op.f('ix_scrapper_name'), table_name='scrapper')
    op.drop_table('scrapper')
    # ### end Alembic commands ###
